use nom::multi::length_data;
use nom::number::streaming::be_u16;
use nom::IResult;
use nom_derive::*;

/// RSA parameters, defined in [RFC2246] section 7.4.3
/// Deprecated, but could appear in RSA_EXPORT cipher suites
/// ServerKeyExchange messages.
#[derive(PartialEq, NomBE, Hash)]
pub struct ServerRSAParams<'a> {
    /// The modulus of the server's temporary RSA key.
    #[nom(Parse = "length_data(be_u16)")]
    pub modulus: &'a [u8],
    /// The public exponent of the server's temporary RSA key.
    #[nom(Parse = "length_data(be_u16)")]
    pub exponent: &'a [u8],
}

#[inline]
pub fn parse_server_rsa_params(i: &[u8]) -> IResult<&[u8], ServerRSAParams> {
    ServerRSAParams::parse(i)
}

#[derive(PartialEq, NomBE, Hash)]
pub struct EncryptedPreMasterSecret<'a> {
    /// The random value generated by the client and encrypted by
    /// the server's public key.
    #[nom(Parse = "length_data(be_u16)")]
    pub data: &'a [u8],
}

#[inline]
pub fn parse_client_rsa_params(i: &[u8]) -> IResult<&[u8], EncryptedPreMasterSecret> {
    EncryptedPreMasterSecret::parse(i)
}
